/*
 * This file is generated by jOOQ.
 */
package lt.liutikas.manga_notification_svc.db.jooq;


import lt.liutikas.manga_notification_svc.db.jooq.tables.MangaChapter;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_MANGA_CHAPTER_SUBSCRIPTION_ID = Internal.createIndex(DSL.name("idx_manga_chapter_subscription_id"), MangaChapter.MANGA_CHAPTER, new OrderField[] { MangaChapter.MANGA_CHAPTER.MANGA_SUBSCRIPTION_ID }, false);
}
