/*
 * This file is generated by jOOQ.
 */
package lt.liutikas.manga_notification_svc.db.jooq;


import lt.liutikas.manga_notification_svc.db.jooq.tables.MangaChapter;
import lt.liutikas.manga_notification_svc.db.jooq.tables.records.JooqMangaChapterRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JooqMangaChapterRecord> MANGA_CHAPTER_PKEY = Internal.createUniqueKey(MangaChapter.MANGA_CHAPTER, DSL.name("manga_chapter_pkey"), new TableField[] { MangaChapter.MANGA_CHAPTER.ID }, true);
}
