/*
 * This file is generated by jOOQ.
 */
package lt.liutikas.manga_notification_svc.db.jooq;


import lt.liutikas.manga_notification_svc.db.jooq.tables.MangaChapter;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.manga_chapter</code>.
     */
    public static final MangaChapter MANGA_CHAPTER = MangaChapter.MANGA_CHAPTER;
}
